# Generated by Django 2.2.1 on 2019-08-10 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.CharField(choices=[('MPA', 'MPA'), ('HRM', 'HRM'), ('IT', 'IT'), ('ECO', 'ECO'), ('ECOMM', 'ECOMM'), ('HRMTUT', 'HRMTUT'), ('ECO TUT', 'ECO TUT'), ('IT TUT', 'IT TUT'), ('MPA TUT', 'MPA TUT')], max_length=10)),
                ('status', models.BooleanField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
